################### {{{ base configuration }}} ###################################

##################################################################################
##################################################################################
server:
  port: 9090
##################################################################################
##################################################################################

##################################################################################
##################################################################################
spring:
  application:
    name: easyCode-logger
  datasource:
    url: jdbc:mysql://localhost:3306/easycode?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver
#################################################################################
#################################################################################

#################################################################################
#################################################################################
mybatis:
  type-aliases-package: com.yfive.modules.**.model
  mapper-locations: classpath*:com/yfive/modules/**/mapping/*.xml
#################################################################################
#################################################################################
