################################# developer environment

## 基本 信息 配置
server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cuserver?useUnicode=true&characterEncoding=utf8&&allowMultiQueries=true
    username: root
    password: mysql
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.escode.storage.po
  mapper-locations: classpath*:com/escode/storage/mybatis/**/*.xml

## 日志 输出 配置
logging:
  level.root: info
  path: logs/

