################################# test environment

## 基本 信息 配置
server:
  port: 8091

spring:
  application:
      name: kaoqinProject
  profiles: test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cuserver?&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
  jackson:
#  time-zone: GMT+8
## 日志 输出 配置
logging:
  level.root: debug
  path: logs/